#!/bin/bash

echo "🗄️  Manual Database Setup Guide"
echo "================================"
echo ""
echo "Step 1: Reset MySQL root password"
echo "Run these commands:"
echo ""
echo "  brew services stop mysql"
echo "  mysqld_safe --skip-grant-tables &"
echo "  # Wait 5 seconds"
echo "  mysql -u root"
echo "  # In MySQL prompt:"
echo "  FLUSH PRIVILEGES;"
echo "  ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';"
echo "  exit;"
echo "  # Kill mysqld_safe process"
echo "  pkill mysqld"
echo "  brew services start mysql"
echo ""
echo "Step 2: Create database and run schema"
echo "  mysql -u root -proot123 << 'SQL'"
echo "  CREATE DATABASE IF NOT EXISTS job_tracker_db;"
echo "  USE job_tracker_db;"
echo "  SOURCE src/main/resources/schema.sql;"
echo "  SQL"
echo ""
echo "Step 3: Update application.properties"
echo "  Change: spring.datasource.password=root123"
echo ""
echo "Step 4: Build and run"
echo "  mvn clean install"
echo "  mvn spring-boot:run"
